# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action
name: 'Check Valid Semver Tag'
description: |
  This action checks if the provided tag is a valid semver tag.

inputs:
  tag:
    description: |
      The tag to check.

    required: true

runs:
  using: composite
  steps:
    - name: 'Check tag'
      id: check-tag
      shell: pwsh
      run: |
        $tag = "${{ inputs.tag }}"
        if ($tag -match '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(alpha|rc|beta|experimental)\.[1-9]\d*)?$') {
          Write-Host "Valid semver" -ForegroundColor Green
          echo "IS_VALID_SEMVER=true" >> $env:GITHUB_OUTPUT
        } else {
          Write-Host "Invalid semver" -ForegroundColor Red
          echo "IS_VALID_SEMVER=false" >> $env:GITHUB_OUTPUT
        }

outputs:
  is-valid-semver:
    value: ${{ steps.check-tag.outputs.IS_VALID_SEMVER }}
    description: |
      If the tag is a valid semver tag.
