FROM fedora:42

RUN dnf install -y \
    clang \
    clang-tools-extra \
    clangd \
    clang-format \
    clang-tidy \
    clang-analyzer \
    cmake \
    git \
    ninja-build \
    mingw64-headers \
    mingw64-crt mingw64-winpthreads mingw64-gcc mingw64-gcc-c++ \
    && dnf clean all
