name: Build DLL

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW
      run: choco install mingw

    - name: Compile DLL
      run: |
        mkdir -p ./build/win32
        g++ -shared -o ./build/main.dll ./src/main.cpp

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: system_tray
        path: build/**/*.dll
