# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
name: 'On Push'
description: |
  This workflow runs on a push.

on:
  push: {}

jobs:
  run:
    name: 'Run'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup and configure CMake'
        uses: './.github/actions/setup_and_configure_cmake'
        with:
          preset: 'windows-vs-release'
